name: gandy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - deepchem=2.4.0
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - optuna=2.5.0
  - pip:
    - tensorflow
    - tensorflow-probability
    - deepchem==2.5.0.dev20210311184720
